name: Continuous Integration
on:
  push:
    branches:
    - main
    paths:
    - version.txt

  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  ci:
    uses: BigGeo-GIV/bg-ci/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      conan_create: true
